"""
test_senso_payload.py — Validates markdown structure generated by build_markdown().
"""
from __future__ import annotations

import pytest

from app.senso_publisher import build_markdown


def _make_event(**overrides) -> dict:
    base = {
        "diff_id": "test-diff-id",
        "payer": "UHC",
        "policy_id": "cardiac-mri",
        "policy_title": "Cardiac MRI Coverage Policy",
        "url": "https://www.uhcprovider.com/en/policies-protocols/b-d/cardiac-mri.html",
        "service_line": "Cardiology",
        "change_type": "TIGHTENING",
        "confidence": 0.92,
        "changed_clause": "Member must have completed a cardiac stress test within the past 6 months.",
        "change_summary": "UHC added a stress test prerequisite before cardiac MRI authorization.",
        "clinical_impact": "Prior authorization teams must collect recent stress test documentation.",
        "cpt_codes_affected": ["75561"],
        "revenue_at_risk_usd": 792000.0,
        "recommended_action": "Update cardiology prior authorization checklist.",
        "markdown_title": "UHC Cardiac MRI Policy Tightened — New Stress Test Requirement Added",
    }
    base.update(overrides)
    return base


class TestBuildMarkdown:

    def test_contains_title(self):
        md = build_markdown(_make_event())
        assert "UHC Cardiac MRI Policy Tightened" in md

    def test_contains_summary_section(self):
        md = build_markdown(_make_event())
        assert "## Summary" in md

    def test_contains_what_changed_section(self):
        md = build_markdown(_make_event())
        assert "## What Changed" in md

    def test_contains_changed_clause_section(self):
        md = build_markdown(_make_event())
        assert "## Changed Clause" in md
        assert "cardiac stress test" in md

    def test_contains_affected_codes_section(self):
        md = build_markdown(_make_event())
        assert "## Affected CPT Codes" in md
        assert "75561" in md

    def test_contains_revenue_impact_section(self):
        md = build_markdown(_make_event())
        assert "## Revenue Impact" in md
        assert "792,000" in md

    def test_contains_recommended_action_section(self):
        md = build_markdown(_make_event())
        assert "## Recommended Action" in md
        assert "prior authorization checklist" in md

    def test_contains_source_section(self):
        md = build_markdown(_make_event())
        assert "## Source" in md
        assert "uhcprovider.com" in md

    def test_revenue_formatted_as_usd(self):
        md = build_markdown(_make_event(revenue_at_risk_usd=261000.0))
        assert "$261,000" in md

    def test_zero_revenue_shows_na(self):
        md = build_markdown(_make_event(revenue_at_risk_usd=0.0))
        assert "N/A" in md

    def test_multiple_cpt_codes_listed(self):
        md = build_markdown(_make_event(cpt_codes_affected=["75557", "75559", "75561"]))
        assert "75557" in md
        assert "75559" in md
        assert "75561" in md

    def test_empty_cpt_codes_shows_none_identified(self):
        md = build_markdown(_make_event(cpt_codes_affected=[]))
        assert "None identified" in md

    def test_changed_clause_in_blockquote(self):
        md = build_markdown(_make_event())
        assert "> Member must have completed a cardiac stress test" in md

    def test_payer_in_what_changed(self):
        md = build_markdown(_make_event())
        assert "UHC" in md

    def test_change_type_in_what_changed(self):
        md = build_markdown(_make_event())
        assert "TIGHTENING" in md
