"use client";

import React from "react";
import Link from "next/link";

interface SensoMarkdownLinkProps {
  citedMdUrl: string;
  eventId: string;
  showViewerLink?: boolean;
}

export default function SensoMarkdownLink({
  citedMdUrl,
  eventId,
  showViewerLink = true,
}: SensoMarkdownLinkProps) {
  if (!citedMdUrl) {
    return (
      <div className="senso-link-empty">
        <span>Senso brief not yet published for this event.</span>
      </div>
    );
  }

  return (
    <div className="senso-link-panel">
      <div className="senso-link-header">
        <span className="senso-label">Senso / cited.md Evidence Brief</span>
        <span className="senso-badge">AI generated</span>
      </div>

      <p className="senso-description">
        A citeable public evidence brief was generated by Senso and published to cited.md. Use it
        to share source-grounded policy intelligence with clinical and revenue teams.
      </p>

      <div className="senso-actions">
        <a
          href={citedMdUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="btn btn-senso btn-lg"
          id={`senso-external-link-${eventId}`}
        >
          Open on cited.md
        </a>

        {showViewerLink ? (
          <Link
            href={`/markdown/${eventId}`}
            className="btn btn-outline btn-lg"
            id={`senso-viewer-link-${eventId}`}
          >
            View inline
          </Link>
        ) : null}
      </div>

      <code className="senso-url">{citedMdUrl}</code>
    </div>
  );
}
